json.extract! stock,
              :id,
              :name,
              :code,
              :updated_at,
              :category,
              :currency,
              :sector,
              :subsector,
              :segment,
              :link
