json.extract! wallet,
              :id,
              :name,
              :user_id,
              :price,
              :price_ratio,
              :market_price,
              :market_price_ratio,
              :market_result,
              :market_result_ratio,
              :earnings,
              :earnings_ratio,
              :payout,
              :payout_ratio,
              :created_at,
              :updated_at,
              :target_percentage,
              :key
