json.extract! wallet,
              :id,
              :name,
              :user_id,
              :total_price,
              :total_market_price,
              :total_earnings,
              :current_payout,
              :price_ratio,
              :market_price_ratio,
              :earnings_ratio,
              :current_payout_rate,
              :created_at,
              :updated_at
