json.extract! user_stock,
              :id,
              :user_id,
              :stock_id,
              :created_at,
              :updated_at,
              :stock_count,
              :average_price_per_stock,
              :total_price,
              :market_price_per_stock,
              :total_market_price,
              :total_earnings,
              :code,
              :category,
              :inactive?,
              :active?
