json.extract! stock_earning,
              :id,
              :per_stock,
              :dy,
              :received_at,
              :category,
              :stock_id,
              :created_at,
              :updated_at,
              :provided_at,
              :code
