json.extract! user_stock_operation,
              :id,
              :nature,
              :user_stock_id,
              :stock_count,
              :stock_price,
              :total,
              :executed_at,
              :created_at,
              :updated_at,
              :code
